"""Main client interface for interacting with LLM providers."""

import logging
from typing import Optional

from config import (
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    OLLAMA_TIMEOUT_SECONDS,
    OLLAMA_TEMPERATURE
)
from llm.providers.base_provider import BaseLLMProvider
from llm.providers.ollama_provider import OllamaProvider

logger = logging.getLogger(__name__)


class LLMClient:
    """Client wrapper for coordinating calls to configured LLM providers."""

    def __init__(self, provider: Optional[BaseLLMProvider] = None) -> None:
        """Initialize the LLM Client.

        By default, initializes the Ollama provider using settings from config.py.
        """
        if provider is None:
            # Local Ollama is the default provider
            self.provider: BaseLLMProvider = OllamaProvider(
                base_url=OLLAMA_BASE_URL,
                model_name=OLLAMA_MODEL,
                timeout=OLLAMA_TIMEOUT_SECONDS,
                temperature=OLLAMA_TEMPERATURE
            )
        else:
            self.provider = provider

        # Retrieve model metadata if available
        self.model_name = getattr(self.provider, "model_name", "unknown")

        # Verify that the configured model exists/is available
        self._verify_model_exists()

    def _verify_model_exists(self) -> None:
        """Run the model availability checks through the provider.

        Raises:
            ValueError: If the configured model is missing/not installed.
            ConnectionError: If the provider is unreachable.
        """
        logger.info("Initializing LLMClient: Verifying model availability metadata...")
        try:
            self.provider.verify_model_exists()
        except ValueError as e:
            logger.error("Model verification failed: %s", str(e))
            raise
        except ConnectionError as e:
            logger.error("Provider connection failed during verification: %s", str(e))
            raise
        except Exception as e:
            logger.error("Unexpected error during model verification: %s", str(e))
            raise ConnectionError(f"Model verification failed: {e}") from e

    def generate(self, prompt: str) -> str:
        """Validate the prompt and generate a completion response using the active provider.

        Args:
            prompt: The string prompt to send to the LLM.

        Returns:
            The stripped string content generated by the provider.

        Raises:
            ValueError: If the prompt is empty or the response is invalid.
            TimeoutError: If the request times out.
            ConnectionError: If connection to the provider fails.
            RuntimeError: For other unexpected failures.
        """
        if not prompt or not prompt.strip():
            logger.error("Request failed: Prompt cannot be empty.")
            raise ValueError("Prompt cannot be empty.")

        logger.info("Request start: model=%s", self.model_name)
        try:
            response_text = self.provider.generate(prompt)
            # Post-processing requirements
            stripped_response = response_text.strip()
            logger.info("Request success: model=%s", self.model_name)
            return stripped_response
        except TimeoutError as e:
            logger.error("Request failure: request timed out for model=%s. Error: %s", self.model_name, str(e))
            raise
        except ConnectionError as e:
            logger.error("Request failure: connection failed for model=%s. Error: %s", self.model_name, str(e))
            raise
        except ValueError as e:
            logger.error("Request failure: invalid response for model=%s. Error: %s", self.model_name, str(e))
            raise
        except Exception as e:
            logger.error("Request failure: unexpected error for model=%s. Error: %s", self.model_name, str(e))
            raise RuntimeError(f"LLM generation failed: {e}") from e
